const express = require('express');
const cors = require('cors');
const routes = require('./routes'); //usa - se ./ para que o node ve como arquivo

const app = express();

app.use(cors());
app.use(express.json());                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
app.use(routes);


app.listen(3333);
